repos:
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
        language_version: python3
        files: ^services/auth

  - repo: local
    hooks:
      - id: eslint
        name: eslint
        entry: bash -c "npm run --prefix services/client lint"
        always_run: true
        language: system

  - repo: local
    hooks:
      - id: stylelint
        name: stylelint
        entry: bash -c "npm run --prefix services/client stylelint"
        always_run: true
        language: system
