version: "3.8"
services:
  auth:
    restart: always
    build:
      context: ./services/auth
      dockerfile: Dockerfile
    volumes:
      - ./services/auth:/usr/src/app
    ports:
      - 5002:5000
    environment:
      - FLASK_ENV=${FLASK_ENV}
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_URL=postgresql://admin:admin@db:5432/tdp
      - APP_CONFIG=${APP_CONFIG}
    networks:
      - database_network
      - web_network
    depends_on:
      - db

  db:
    image: postgres:12-alpine
    volumes:
      - db-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=tdp
    networks:
      - database_network

  client:
    build:
      context: ./services/client
      dockerfile: Dockerfile
    volumes:
      - ./services/client:/usr/src/client
      - /usr/src/client/node_modules
    ports:
      - 3005:3000
    environment:
      - NODE_ENV=${NODE_ENV}
    networks:
      - web_network

  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - 80:80
      - 443:443
    networks:
      - web_network
    depends_on:
      - auth
      - client
      - pgadmin

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 5055:5050
    environment:
      - PGADMIN_LISTEN_PORT=5050
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    networks:
      - web_network
      - database_network
    depends_on:
      - db

volumes:
  db-data:

networks:
  database_network:
    driver: bridge

  web_network:
    driver: bridge
