version: "3.8"
services:
  auth:
    build:
      context: ./services/auth
      dockerfile: Dockerfile
    volumes:
      - ./services/auth:/usr/src/app
    ports:
      - 5002:5000
    environment:
      - FLASK_ENV=development
      - SECRET_KEY=tdp-auth
      - DB_URL=postgresql://admin:admin@db:5432/tdp
      - APP_CONFIG=app.config.DevConfig
    depends_on:
      - postgres

  postgres:
    restart: always
    image: postgres:latest
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USERNAME=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DATABASE=td
    ports:
      - "5433:5432"

  client:
    build:
      context: ./services/client
      dockerfile: Dockerfile
    volumes:
      - ./services/client:/usr/src/client
      - /usr/src/client/node_modules
    ports:
      - 3005:3000
    environment:
      - NODE_ENV=development

volumes:
  db-data:
